# Generated by Django 2.2.16 on 2022-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='confirmation_code',
            field=models.CharField(max_length=36, verbose_name='Код подтверждения'),
        ),
    ]
