# Generated by Django 2.2.16 on 2022-06-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220623_2347'),
        ('reviews', '0002_auto_20220627_2147'),
    ]

    operations = [
    ]
